#!/usr/bin/env python3
"""
gen_per_pin.py  --  generate solid_core.i for the per-pin-sideset coupling.

WHY: the CoupledHeatTransfers action does NOT support partitioning one shared
'outer' sideset across N position-keyed channels (verified against MOOSE source;
no test exercises >1 point, and it collapses to a whole-boundary average -> every
channel removed the same ~568 W). The ONLY source-tested configuration is N
single-channel couplings, each on its OWN sideset, each driving its OWN
single-instance THM app. This script emits exactly that: it splits 'outer' into 37
per-pin sidesets and writes 37 single-channel CoupledHeatTransfers + 37 THM apps.

Re-run after any change to pin_positions.txt or the physics template below:
    python gen_per_pin.py        # writes solid_core.i

The OpenMC<->solid half is unchanged and lives in openmc.i (the main app). thm.i is
unchanged (now launched 37x as separate single-instance apps).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
L = 0.310515            # active length [m]
ZBASE = -L / 2.0        # -0.1552575; the centered mesh spans z in [-L/2, +L/2]
N_AX = 30
HW = 5.01e4
RSEL2 = 0.016 ** 2      # proximity radius^2 (~pitch/2) to assign an 'outer' face to its pin

# ---- read the 37 pin centers --------------------------------------------------
pins = []
with open(os.path.join(HERE, "pin_positions.txt")) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        x, y, z = (float(v) for v in line.split())
        pins.append((x, y))
assert len(pins) == 37, f"expected 37 pins in pin_positions.txt, got {len(pins)}"

# ---- per-pin mesh sidesets: subdivide 'outer' by (x,y) proximity --------------
# Each face already on 'outer' (the radial clad surface) is assigned to the pin
# whose center it is within ~pitch/2 of. included_boundaries restricts to existing
# 'outer' faces, so no internal/azimuthal/cap faces are caught.
sideset_blocks = []
prev = "core"
for i, (x, y) in enumerate(pins, start=1):
    name = f"outer_p{i:02d}"
    sideset_blocks.append(f"""  [{name}]
    type = ParsedGenerateSideset
    input = {prev}
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - {x:.7f})^2 + (y - {y:.7f})^2 < {RSEL2:.6e}'
    new_sideset_name = '{name}'
  []""")
    prev = name
sideset_str = "\n".join(sideset_blocks)

# ---- 37 single-instance THM apps + 37 single-channel couplings ----------------
multiapp_blocks = []
cht_blocks = []
for i, (x, y) in enumerate(pins, start=1):
    pos = f"{x:.7f} {y:.7f} {ZBASE:.7f}"
    multiapp_blocks.append(f"""  [thm{i:02d}]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '{pos}'
    execute_on = timestep_end
    sub_cycling = true
  []""")
    cht_blocks.append(f"""  [p{i:02d}]
    boundary = 'outer_p{i:02d}'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm{i:02d}
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '{pos}'
    orientation = '0 0 1'
    length = {L}
    n_elems = {N_AX}
    skip_coordinate_collapsing = true
  []""")
multiapp_str = "\n".join(multiapp_blocks)
cht_str = "\n".join(cht_blocks)

# ---- assemble solid_core.i ----------------------------------------------------
deck = f"""# =============================================================================
# Layer 2: 37-pin core conduction + NaK -- SOLID sub-app  (GENERATED by gen_per_pin.py)
# =============================================================================
# DO NOT EDIT BY HAND. Edit gen_per_pin.py and re-run it. This file is a SUB-APP of
# openmc.i (OpenMC is the main app). Run the coupled model with:
#   cardinal-opt -i openmc.i        (NOT this file directly)
#
# PER-PIN COUPLING: the CoupledHeatTransfers action cannot partition one shared
# 'outer' sideset across 37 channels (unsupported MOOSE mode; it collapses to a
# whole-boundary average). So 'outer' is split into 37 per-pin sidesets
# (outer_p01..outer_p37), each driven by its OWN single-channel CoupledHeatTransfers
# block and its OWN single-instance THM app (thm01..thm37). This is the only
# source-tested configuration. Each pin's clad surface couples to its own NaK channel.
#
#   openmc.i (main) --power--> THIS (solid) --T_wall_pNN--> thm{{NN}}.i (37 apps)
#        <-- temperature --              <-- T_fluid / htc --
# =============================================================================

L    = {L}
n_ax = {N_AX}
Hw   = {HW}

[Mesh]
  [core]
    type = FileMeshGenerator
    file = core37.e
  []
  # --- 37 per-pin clad sidesets, carved out of the single 'outer' sideset --------
{sideset_str}
[]

[Variables]
  [T]
    initial_condition = 783.15
  []
[]

[AuxVariables]
  [power]                 # filled by the transfer from the OpenMC parent (heat_source)
    family = MONOMIAL
    order = CONSTANT
    block = fuel
  []
  [T_fluid]               # filled by the per-pin CoupledHeatTransfers from THM
    family = MONOMIAL
    order = CONSTANT
    initial_condition = 755.37
  []
  [htc]
    family = MONOMIAL
    order = CONSTANT
    initial_condition = ${{Hw}}
  []
[]

[Kernels]
  [conduction]
    type = HeatConduction
    variable = T
  []
  # NO time-derivative kernel: steady conduction each Picard step (gas_assembly pattern).
  [source]
    type = CoupledForce
    variable = T
    v = power
    block = fuel
  []
[]

# ---- NaK conjugate coupling: 37 single-channel couplings, one per pin sideset --
# Each block is the source-tested single-channel form (no positions_file): boundary
# = that pin's own sideset, a single position on that pin's axis (x,y, z=-L/2 to match
# the centered mesh), and its own single-instance THM app. Generated from pin_positions.txt.
[CoupledHeatTransfers]
{cht_str}
[]

[MultiApps]
{multiapp_str}
[]

# The OpenMC <-> solid power/temperature transfers live in the parent openmc.i.

[Materials]
  [fuel_mat]
    type = GenericConstantMaterial
    block = fuel
    prop_names  = 'thermal_conductivity density specific_heat'
    prop_values = '22.484 6000.0 300.0'
  []
  [coating_mat]
    type = GenericConstantMaterial
    block = coating
    prop_names  = 'thermal_conductivity density specific_heat'
    prop_values = '1.729 7400.0 400.0'
  []
  [clad_k]
    type = PiecewiseLinearInterpolationMaterial
    block = clad
    property = thermal_conductivity
    variable = T
    extrapolation = true
    x = '300   400   500   600   700   800   900   1000  1100'
    y = '10.99 11.98 13.26 14.83 16.70 18.86 21.31 24.05 27.08'
  []
  [clad_rhocp]
    type = GenericConstantMaterial
    block = clad
    prop_names  = 'density specific_heat'
    prop_values = '8860.0 578.0'
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  # Conjugate inner loop (the OpenMC parent calls this as a FullSolveMultiApp once per
  # outer step). The fixed_point loop converges the solid<->THM coupling against the
  # frozen heat source; THM (37 apps, sub_cycling) re-solves each iteration. Stops
  # early on the tol. If the stiff (high-Hw) conjugate is slow, relax the interface:
  #   relaxation_factor = 0.7 ; transformed_variables = 'T_fluid'
  type = Transient
  scheme = bdf2
  start_time = 0
  dt = 100.0
  num_steps = 1
  fixed_point_max_its = 50
  fixed_point_rel_tol = 1e-4
  fixed_point_abs_tol = 1e-2
  accept_on_max_fixed_point_iteration = true
  solve_type = NEWTON
  petsc_options_iname = '-pc_type'
  petsc_options_value = ' lu'
  nl_rel_tol = 1e-7
  nl_abs_tol = 1e-6
  l_max_its = 100
[]

[Postprocessors]
  [power_in]
    type = ElementIntegralVariablePostprocessor
    variable = power
    block = fuel
    execute_on = 'transfer initial timestep_end'
  []
  [max_fuel_T]
    type = ElementExtremeValue
    variable = T
    block = fuel
    value_type = max
  []
  [surface_heat_out]
    type = SideDiffusiveFluxIntegral
    variable = T
    boundary = 'outer'
    diffusivity = thermal_conductivity
    execute_on = 'initial timestep_end'
  []
  [power_imbalance]
    type = ParsedPostprocessor
    expression = 'power_in - surface_heat_out'
    pp_names = 'power_in surface_heat_out'
    execute_on = 'initial timestep_end'
  []
[]

[Outputs]
  exodus = true
  [csv]
    type = CSV
    file_base = solid_core
  []
  [console]
    type = Console
    show = 'power_in surface_heat_out power_imbalance max_fuel_T'
  []
[]
"""

with open(os.path.join(HERE, "solid_core.i"), "w") as f:
    f.write(deck)
print(f"wrote solid_core.i: {len(pins)} pins -> {len(sideset_blocks)} sidesets, "
      f"{len(multiapp_blocks)} THM apps, {len(cht_blocks)} couplings")
