# =============================================================================
# Layer 2: 37-pin core conduction + NaK -- SOLID sub-app  (GENERATED by gen_per_pin.py)
# =============================================================================
# DO NOT EDIT BY HAND. Edit gen_per_pin.py and re-run it. This file is a SUB-APP of
# openmc.i (OpenMC is the main app). Run the coupled model with:
#   cardinal-opt -i openmc.i        (NOT this file directly)
#
# PER-PIN COUPLING: the CoupledHeatTransfers action cannot partition one shared
# 'outer' sideset across 37 channels (unsupported MOOSE mode; it collapses to a
# whole-boundary average). So 'outer' is split into 37 per-pin sidesets
# (outer_p01..outer_p37), each driven by its OWN single-channel CoupledHeatTransfers
# block and its OWN single-instance THM app (thm01..thm37). This is the only
# source-tested configuration. Each pin's clad surface couples to its own NaK channel.
#
#   openmc.i (main) --power--> THIS (solid) --T_wall_pNN--> thm{NN}.i (37 apps)
#        <-- temperature --              <-- T_fluid / htc --
# =============================================================================

L    = 0.310515
n_ax = 30
Hw   = 50100.0

[Mesh]
  [core]
    type = FileMeshGenerator
    file = core37.e
  []
  # --- 37 per-pin clad sidesets, carved out of the single 'outer' sideset --------
  [outer_p01]
    type = ParsedGenerateSideset
    input = core
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - 0.0000000)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p01'
  []
  [outer_p02]
    type = ParsedGenerateSideset
    input = outer_p01
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - 0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p02'
  []
  [outer_p03]
    type = ParsedGenerateSideset
    input = outer_p02
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - 0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p03'
  []
  [outer_p04]
    type = ParsedGenerateSideset
    input = outer_p03
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - 0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p04'
  []
  [outer_p05]
    type = ParsedGenerateSideset
    input = outer_p04
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - -0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p05'
  []
  [outer_p06]
    type = ParsedGenerateSideset
    input = outer_p05
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - -0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p06'
  []
  [outer_p07]
    type = ParsedGenerateSideset
    input = outer_p06
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - -0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p07'
  []
  [outer_p08]
    type = ParsedGenerateSideset
    input = outer_p07
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0554325)^2 + (y - 0.0000000)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p08'
  []
  [outer_p09]
    type = ParsedGenerateSideset
    input = outer_p08
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0554325)^2 + (y - 0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p09'
  []
  [outer_p10]
    type = ParsedGenerateSideset
    input = outer_p09
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - 0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p10'
  []
  [outer_p11]
    type = ParsedGenerateSideset
    input = outer_p10
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - 0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p11'
  []
  [outer_p12]
    type = ParsedGenerateSideset
    input = outer_p11
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - 0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p12'
  []
  [outer_p13]
    type = ParsedGenerateSideset
    input = outer_p12
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0554325)^2 + (y - 0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p13'
  []
  [outer_p14]
    type = ParsedGenerateSideset
    input = outer_p13
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0554325)^2 + (y - 0.0000000)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p14'
  []
  [outer_p15]
    type = ParsedGenerateSideset
    input = outer_p14
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0554325)^2 + (y - -0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p15'
  []
  [outer_p16]
    type = ParsedGenerateSideset
    input = outer_p15
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - -0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p16'
  []
  [outer_p17]
    type = ParsedGenerateSideset
    input = outer_p16
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - -0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p17'
  []
  [outer_p18]
    type = ParsedGenerateSideset
    input = outer_p17
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - -0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p18'
  []
  [outer_p19]
    type = ParsedGenerateSideset
    input = outer_p18
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0554325)^2 + (y - -0.0320040)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p19'
  []
  [outer_p20]
    type = ParsedGenerateSideset
    input = outer_p19
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0831488)^2 + (y - 0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p20'
  []
  [outer_p21]
    type = ParsedGenerateSideset
    input = outer_p20
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0831488)^2 + (y - 0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p21'
  []
  [outer_p22]
    type = ParsedGenerateSideset
    input = outer_p21
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0554325)^2 + (y - 0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p22'
  []
  [outer_p23]
    type = ParsedGenerateSideset
    input = outer_p22
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - 0.0800100)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p23'
  []
  [outer_p24]
    type = ParsedGenerateSideset
    input = outer_p23
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - 0.0960120)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p24'
  []
  [outer_p25]
    type = ParsedGenerateSideset
    input = outer_p24
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - 0.0800100)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p25'
  []
  [outer_p26]
    type = ParsedGenerateSideset
    input = outer_p25
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0554325)^2 + (y - 0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p26'
  []
  [outer_p27]
    type = ParsedGenerateSideset
    input = outer_p26
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0831488)^2 + (y - 0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p27'
  []
  [outer_p28]
    type = ParsedGenerateSideset
    input = outer_p27
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0831488)^2 + (y - 0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p28'
  []
  [outer_p29]
    type = ParsedGenerateSideset
    input = outer_p28
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0831488)^2 + (y - -0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p29'
  []
  [outer_p30]
    type = ParsedGenerateSideset
    input = outer_p29
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0831488)^2 + (y - -0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p30'
  []
  [outer_p31]
    type = ParsedGenerateSideset
    input = outer_p30
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0554325)^2 + (y - -0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p31'
  []
  [outer_p32]
    type = ParsedGenerateSideset
    input = outer_p31
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - -0.0277162)^2 + (y - -0.0800100)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p32'
  []
  [outer_p33]
    type = ParsedGenerateSideset
    input = outer_p32
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0831488)^2 + (y - -0.0160020)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p33'
  []
  [outer_p34]
    type = ParsedGenerateSideset
    input = outer_p33
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0831488)^2 + (y - -0.0480060)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p34'
  []
  [outer_p35]
    type = ParsedGenerateSideset
    input = outer_p34
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0554325)^2 + (y - -0.0640080)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p35'
  []
  [outer_p36]
    type = ParsedGenerateSideset
    input = outer_p35
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0277162)^2 + (y - -0.0800100)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p36'
  []
  [outer_p37]
    type = ParsedGenerateSideset
    input = outer_p36
    included_boundaries = 'outer'
    combinatorial_geometry = '(x - 0.0000000)^2 + (y - -0.0960120)^2 < 2.560000e-04'
    new_sideset_name = 'outer_p37'
  []
[]

[Variables]
  [T]
    initial_condition = 783.15
  []
[]

[AuxVariables]
  [power]                 # filled by the transfer from the OpenMC parent (heat_source)
    family = MONOMIAL
    order = CONSTANT
    block = fuel
  []
  [T_fluid]               # filled by the per-pin CoupledHeatTransfers from THM
    family = MONOMIAL
    order = CONSTANT
    initial_condition = 755.37
  []
  [htc]
    family = MONOMIAL
    order = CONSTANT
    initial_condition = ${Hw}
  []
[]

[Kernels]
  [conduction]
    type = HeatConduction
    variable = T
  []
  # NO time-derivative kernel: steady conduction each Picard step (gas_assembly pattern).
  [source]
    type = CoupledForce
    variable = T
    v = power
    block = fuel
  []
[]

# ---- NaK conjugate coupling: 37 single-channel couplings, one per pin sideset --
# Each block is the source-tested single-channel form (no positions_file): boundary
# = that pin's own sideset, a single position on that pin's axis (x,y, z=-L/2 to match
# the centered mesh), and its own single-instance THM app. Generated from pin_positions.txt.
[CoupledHeatTransfers]
  [p01]
    boundary = 'outer_p01'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm01
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 0.0000000 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p02]
    boundary = 'outer_p02'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm02
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p03]
    boundary = 'outer_p03'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm03
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p04]
    boundary = 'outer_p04'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm04
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p05]
    boundary = 'outer_p05'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm05
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 -0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p06]
    boundary = 'outer_p06'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm06
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 -0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p07]
    boundary = 'outer_p07'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm07
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 -0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p08]
    boundary = 'outer_p08'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm08
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0554325 0.0000000 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p09]
    boundary = 'outer_p09'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm09
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0554325 0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p10]
    boundary = 'outer_p10'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm10
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p11]
    boundary = 'outer_p11'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm11
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p12]
    boundary = 'outer_p12'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm12
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p13]
    boundary = 'outer_p13'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm13
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0554325 0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p14]
    boundary = 'outer_p14'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm14
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0554325 0.0000000 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p15]
    boundary = 'outer_p15'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm15
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0554325 -0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p16]
    boundary = 'outer_p16'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm16
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 -0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p17]
    boundary = 'outer_p17'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm17
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 -0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p18]
    boundary = 'outer_p18'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm18
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 -0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p19]
    boundary = 'outer_p19'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm19
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0554325 -0.0320040 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p20]
    boundary = 'outer_p20'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm20
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0831488 0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p21]
    boundary = 'outer_p21'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm21
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0831488 0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p22]
    boundary = 'outer_p22'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm22
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0554325 0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p23]
    boundary = 'outer_p23'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm23
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 0.0800100 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p24]
    boundary = 'outer_p24'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm24
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 0.0960120 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p25]
    boundary = 'outer_p25'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm25
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 0.0800100 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p26]
    boundary = 'outer_p26'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm26
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0554325 0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p27]
    boundary = 'outer_p27'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm27
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0831488 0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p28]
    boundary = 'outer_p28'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm28
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0831488 0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p29]
    boundary = 'outer_p29'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm29
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0831488 -0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p30]
    boundary = 'outer_p30'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm30
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0831488 -0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p31]
    boundary = 'outer_p31'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm31
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0554325 -0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p32]
    boundary = 'outer_p32'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm32
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '-0.0277162 -0.0800100 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p33]
    boundary = 'outer_p33'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm33
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0831488 -0.0160020 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p34]
    boundary = 'outer_p34'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm34
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0831488 -0.0480060 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p35]
    boundary = 'outer_p35'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm35
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0554325 -0.0640080 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p36]
    boundary = 'outer_p36'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm36
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0277162 -0.0800100 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
  [p37]
    boundary = 'outer_p37'
    T = T
    T_fluid = 'T_fluid'
    T_wall = T_wall
    htc = 'htc'
    multi_app = thm37
    T_fluid_user_objects = 'T_uo'
    htc_user_objects = 'Hw_uo'
    position = '0.0000000 -0.0960120 -0.1552575'
    orientation = '0 0 1'
    length = 0.310515
    n_elems = 30
    skip_coordinate_collapsing = true
  []
[]

[MultiApps]
  [thm01]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 0.0000000 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm02]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm03]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm04]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm05]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 -0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm06]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 -0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm07]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 -0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm08]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0554325 0.0000000 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm09]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0554325 0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm10]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm11]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm12]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm13]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0554325 0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm14]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0554325 0.0000000 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm15]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0554325 -0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm16]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 -0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm17]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 -0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm18]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 -0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm19]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0554325 -0.0320040 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm20]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0831488 0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm21]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0831488 0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm22]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0554325 0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm23]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 0.0800100 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm24]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 0.0960120 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm25]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 0.0800100 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm26]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0554325 0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm27]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0831488 0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm28]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0831488 0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm29]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0831488 -0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm30]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0831488 -0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm31]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0554325 -0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm32]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '-0.0277162 -0.0800100 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm33]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0831488 -0.0160020 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm34]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0831488 -0.0480060 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm35]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0554325 -0.0640080 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm36]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0277162 -0.0800100 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
  [thm37]
    type = TransientMultiApp
    input_files = 'thm.i'
    positions = '0.0000000 -0.0960120 -0.1552575'
    execute_on = timestep_end
    sub_cycling = true
  []
[]

# The OpenMC <-> solid power/temperature transfers live in the parent openmc.i.

[Materials]
  [fuel_mat]
    type = GenericConstantMaterial
    block = fuel
    prop_names  = 'thermal_conductivity density specific_heat'
    prop_values = '22.484 6000.0 300.0'
  []
  [coating_mat]
    type = GenericConstantMaterial
    block = coating
    prop_names  = 'thermal_conductivity density specific_heat'
    prop_values = '1.729 7400.0 400.0'
  []
  [clad_k]
    type = PiecewiseLinearInterpolationMaterial
    block = clad
    property = thermal_conductivity
    variable = T
    extrapolation = true
    x = '300   400   500   600   700   800   900   1000  1100'
    y = '10.99 11.98 13.26 14.83 16.70 18.86 21.31 24.05 27.08'
  []
  [clad_rhocp]
    type = GenericConstantMaterial
    block = clad
    prop_names  = 'density specific_heat'
    prop_values = '8860.0 578.0'
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  # Conjugate inner loop (the OpenMC parent calls this as a FullSolveMultiApp once per
  # outer step). The fixed_point loop converges the solid<->THM coupling against the
  # frozen heat source; THM (37 apps, sub_cycling) re-solves each iteration. Stops
  # early on the tol. If the stiff (high-Hw) conjugate is slow, relax the interface:
  #   relaxation_factor = 0.7 ; transformed_variables = 'T_fluid'
  type = Transient
  scheme = bdf2
  start_time = 0
  dt = 100.0
  num_steps = 1
  fixed_point_max_its = 50
  fixed_point_rel_tol = 1e-4
  fixed_point_abs_tol = 1e-2
  accept_on_max_fixed_point_iteration = true
  solve_type = NEWTON
  petsc_options_iname = '-pc_type'
  petsc_options_value = ' lu'
  nl_rel_tol = 1e-7
  nl_abs_tol = 1e-6
  l_max_its = 100
[]

[Postprocessors]
  [power_in]
    type = ElementIntegralVariablePostprocessor
    variable = power
    block = fuel
    execute_on = 'transfer initial timestep_end'
  []
  [max_fuel_T]
    type = ElementExtremeValue
    variable = T
    block = fuel
    value_type = max
  []
  [surface_heat_out]
    type = SideDiffusiveFluxIntegral
    variable = T
    boundary = 'outer'
    diffusivity = thermal_conductivity
    execute_on = 'initial timestep_end'
  []
  [power_imbalance]
    type = ParsedPostprocessor
    expression = 'power_in - surface_heat_out'
    pp_names = 'power_in surface_heat_out'
    execute_on = 'initial timestep_end'
  []
[]

[Outputs]
  exodus = true
  [csv]
    type = CSV
    file_base = solid_core
  []
  [console]
    type = Console
    show = 'power_in surface_heat_out power_imbalance max_fuel_T'
  []
[]
